services:

  spring:
    image: "tms-spring"
    container_name: tms-spring
    build:
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT=8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tmsdb


  postgres:
    image: postgres:latest
    container_name: tms-db
    restart: always
    environment:
      POSTGRES_DB: tmsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
