version: '3.8'

services:
  tms-spring:
    build: .
    image: task-management-system-java
    ports:
      - "8060:8060"
    environment:
      - DB_HOST=tms-db
      - DB_PORT=5432
      - DB_NAME=tms
      - DB_USER=admin
      - DB_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tms-db:5432/tmsdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - tms-db

  tms-db:
    image: postgres:17
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tmsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: